### ISSUE TITLE
[CONFIG] Provides an .env.example

### ISSUE THREAD

**Issue by davorpa** [Retropia-Market/retropia-backend#16]
Hi

First of all, congratulations for this great project. The appearance is fantastic.

I see that dotconf is used to manage environment variables.

Is it possible provide a `.env.example` in the project root folder with the env keys used by the app. It'll also be fine if some comment is appended about if are optional, how to fill it, format...

Its a bit difficult try to start server and see it crashing, and have to search what is the next I need to search.

Thanks in advance.

**Comment by ivan-gal** [comment]
Hi Davorpa, I uploded it. I will check the other issue now.

Thank you.
